version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      # Service container image available at `host: localhost`

      - image: circleci/postgres:9.6.9-postgis
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: el_documento
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - restore_cache:
          key: scala-library-dependencies-{{ checksum "build.sbt" }}
      - run:
           name: compile
           command: sbt test:compile
      - run: sbt test:flywayClean
      - run:
          name: migrate database for test
          command: sbt test:flywayMigrate
      - save_cache:
          paths: [ "~/.m2", "~/.ivy2", "~/.cache/coursier" ]
          key: scala-library-dependencies-{{ checksum "build.sbt" }}
      - run: sbt clean coverage test coverageReport
      - run: bash <(curl -s https://codecov.io/bash)